version: '3.8'

services:
  # 1. API GATEWAY
  gateway_service:
    build: ./gateway_service
    container_name: api_gateway
    ports:
      - "8000:8000" 
    environment:
      - RESERVATION_URL=http://reservation_service:8004
      - INVENTORY_URL=http://inventory_service:8001
      - PAYMENT_URL=http://payment_service:8002
      - NOTIFICATION_URL=http://notification_service:8003
    depends_on:
      - reservation_service
    networks:
      - reserva_net

  # 2. SERVICIO DE RESERVAS (Core)
  reservation_service:
    build: ./reservation_service
    container_name: core_reservation
    environment:
      - INVENTORY_URL=http://inventory_service:8001
      - PAYMENT_URL=http://payment_service:8002
      - NOTIFICATION_URL=http://notification_service:8003
    depends_on:
      - inventory_service
      - payment_service
    volumes:
      - ./data_reservas:/app/data
    networks:
      - reserva_net

  # 3. STUBS (Inventario, Pagos, Notificaciones)
  inventory_service:
    build: ./inventory_service
    container_name: inventory_stub
    environment:
      - FAILURE_MODE=crash
    ports:
      - "8001:8001"
    volumes:
      - ./data_inventory:/app/data
    networks:
      - reserva_net

  payment_service:
    build: ./payment_service
    container_name: payment_stub
    environment:
      - FAILURE_MODE=none
    ports:
      - "8002:8002"
    networks:
      - reserva_net

  notification_service:
    build: ./notification_service
    container_name: notification_worker
    environment:
      - EMAIL_PROVIDER=mock
    ports:
      - "8003:8003"
    networks:
      - reserva_net

networks:
  reserva_net:
    driver: bridge